// This file will be auto-generated by: supabase gen types typescript
// For now, define a minimal placeholder so imports work.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type NotificationType =
  | "connection_request"
  | "meeting_request"
  | "meeting_confirmed"
  | "meeting_summary"
  | "introduction_request"
  | "introduction_completed"
  | "new_match_weekly"
  | "new_match_high"
  | "mutual_match"
  | "maturity_up"
  | "contact_exchange"
  | "intervention_alert"
  | "followup_reminder"
  | "system";

export type ConnectionStatus =
  | "pending"
  | "accepted"
  | "declined"
  | "cancelled"
  | "disconnected"
  | "blocked"
  | "reaccepted";

export type TranscriptStatus =
  | "pending"
  | "fetching"
  | "ready"
  | "analyzing"
  | "analyzed"
  | "error";

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
type R = { Relationships: [] };

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          name: string;
          email: string;
          company: string | null;
          position: string | null;
          industry: string | null;
          bio: string | null;
          avatar_url: string | null;
          cover_url: string | null;
          contact_info: string | null;
          is_admin: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          company?: string | null;
          position?: string | null;
          industry?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          cover_url?: string | null;
          contact_info?: string | null;
          is_admin?: boolean;
          is_active?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["user_profiles"]["Insert"]>;
        Relationships: [];
      };
      connections: {
        Row: {
          id: string;
          user_id: string;
          connected_user_id: string;
          status: ConnectionStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          connected_user_id: string;
          status?: ConnectionStatus;
        };
        Update: {
          status?: ConnectionStatus;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: NotificationType;
          title: string;
          message: string;
          link: string | null;
          actions: Json | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          type: NotificationType;
          title: string;
          message: string;
          link?: string | null;
          actions?: Json | null;
          is_read?: boolean;
        };
        Update: {
          is_read?: boolean;
        };
        Relationships: [];
      };
      meeting_transcripts: {
        Row: {
          id: string;
          tldv_meeting_id: string;
          title: string | null;
          meeting_date: string | null;
          full_text: string | null;
          status: TranscriptStatus;
          error_message: string | null;
          fetched_at: string | null;
          created_at: string;
        };
        Insert: {
          tldv_meeting_id: string;
          title?: string | null;
          meeting_date?: string | null;
          full_text?: string | null;
          status?: TranscriptStatus;
        };
        Update: Partial<
          Database["public"]["Tables"]["meeting_transcripts"]["Insert"]
        >;
        Relationships: [];
      };
      meeting_participants: {
        Row: {
          id: string;
          transcript_id: string;
          user_id: string | null;
          speaker_name: string;
          email: string | null;
          speaking_ratio: number | null;
          is_linked: boolean;
          linked_method: string | null;
          created_at: string;
        };
        Insert: {
          transcript_id: string;
          speaker_name: string;
          user_id?: string | null;
          email?: string | null;
          speaking_ratio?: number | null;
          is_linked?: boolean;
          linked_method?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["meeting_participants"]["Insert"]
        >;
        Relationships: [];
      };
      transcript_insights: {
        Row: {
          id: string;
          transcript_id: string;
          participant_id: string;
          demonstrated_skills: string[];
          expressed_needs: string[];
          offered_capabilities: string[];
          communication_traits: Json;
          key_statements: string[];
          engagement_metrics: Json;
          confidence_score: number | null;
          prompt_version: string | null;
          created_at: string;
        };
        Insert: {
          transcript_id: string;
          participant_id: string;
          demonstrated_skills?: string[];
          expressed_needs?: string[];
          offered_capabilities?: string[];
          communication_traits?: Json;
          key_statements?: string[];
          engagement_metrics?: Json;
          confidence_score?: number | null;
          prompt_version?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["transcript_insights"]["Insert"]
        >;
        Relationships: [];
      };
      member_ai_profiles_v2: {
        Row: {
          id: string;
          user_id: string;
          aggregated_skills: Json[];
          aggregated_needs: Json[];
          aggregated_offerings: Json[];
          communication_profile: Json;
          analysis_count: number;
          last_analyzed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          aggregated_skills?: Json[];
          aggregated_needs?: Json[];
          aggregated_offerings?: Json[];
          communication_profile?: Json;
          analysis_count?: number;
          last_analyzed_at?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["member_ai_profiles_v2"]["Insert"]
        >;
        Relationships: [];
      };
      matching_scores_v3: {
        Row: {
          id: string;
          viewer_id: string;
          target_id: string;
          value_fit: number;
          relational_quality: number;
          total_score: number;
          confidence: number;
          phase: string;
          score_reasons: Json;
          notify_tier: string | null;
          is_stale: boolean;
          calculated_at: string;
        };
        Insert: {
          viewer_id: string;
          target_id: string;
          value_fit?: number;
          relational_quality?: number;
          total_score?: number;
          confidence?: number;
          phase?: string;
          score_reasons?: Json;
          notify_tier?: string | null;
          is_stale?: boolean;
        };
        Update: Partial<
          Database["public"]["Tables"]["matching_scores_v3"]["Insert"]
        >;
        Relationships: [];
      };
      mutual_match_notifications: {
        Row: {
          id: string;
          user_a_id: string;
          user_b_id: string;
          notified_at: string;
        };
        Insert: {
          user_a_id: string;
          user_b_id: string;
        };
        Update: never;
        Relationships: [];
      };
      // match_requests / match_connections は meeting_requests / connections に統合済み (削除)
      profile_views: {
        Row: {
          id: string;
          viewer_id: string;
          viewed_user_id: string;
          view_duration: number | null;
          viewed_at: string;
        };
        Insert: {
          viewer_id: string;
          viewed_user_id: string;
          view_duration?: number | null;
        };
        Update: never;
        Relationships: [];
      };
      bookmarks: {
        Row: {
          id: string;
          user_id: string;
          bookmarked_user_id: string;
          note: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          bookmarked_user_id: string;
          note?: string | null;
        };
        Update: {
          note?: string | null;
        };
        Relationships: [];
      };
      settings: {
        Row: {
          id: string;
          user_id: string;
          theme: string;
          notifications_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          theme?: string;
          notifications_enabled?: boolean;
        };
        Update: {
          theme?: string;
          notifications_enabled?: boolean;
        };
        Relationships: [];
      };
      prompt_versions: {
        Row: {
          id: string;
          name: string;
          version: string;
          template: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          name: string;
          version: string;
          template: string;
          is_active?: boolean;
        };
        Update: {
          is_active?: boolean;
          template?: string;
        };
        Relationships: [];
      };
      login_sessions: {
        Row: {
          id: string;
          user_id: string;
          device: string | null;
          browser: string | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          device?: string | null;
          browser?: string | null;
          ip_address?: string | null;
        };
        Update: never;
        Relationships: [];
      };
      invitation_codes: {
        Row: {
          id: string;
          code: string;
          created_by: string | null;
          used_by: string | null;
          max_uses: number;
          use_count: number;
          expires_at: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          code: string;
          created_by?: string | null;
          max_uses?: number;
          expires_at?: string | null;
        };
        Update: {
          used_by?: string | null;
          use_count?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      user_goals: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          context: string | null;
          confidence: number;
          source: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          type: string;
          context?: string | null;
          confidence?: number;
          source?: string;
        };
        Update: {
          context?: string | null;
          confidence?: number;
        };
        Relationships: [];
      };
      user_offerings: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          context: string | null;
          confidence: number;
          source: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          type: string;
          context?: string | null;
          confidence?: number;
          source?: string;
        };
        Update: {
          context?: string | null;
          confidence?: number;
        };
        Relationships: [];
      };
      meeting_requests: {
        Row: {
          id: string; requester_id: string; target_id: string;
          message: string | null; proposed_times: Json;
          status: string; created_at: string; updated_at: string;
        };
        Insert: {
          requester_id: string; target_id: string;
          message?: string | null; proposed_times?: Json; status?: string;
        };
        Update: { status?: string; };
        Relationships: [];
      };
      meetings: {
        Row: {
          id: string; request_id: string | null; title: string | null;
          scheduled_at: string; duration_min: number; platform: string;
          meeting_url: string | null; status: string;
          created_at: string; updated_at: string;
        };
        Insert: {
          request_id?: string | null; title?: string | null;
          scheduled_at: string; duration_min?: number; platform?: string;
          meeting_url?: string | null; status?: string;
        };
        Update: { title?: string; status?: string; meeting_url?: string; updated_at?: string; };
        Relationships: [];
      };
      meeting_participants_v2: {
        Row: {
          id: string; meeting_id: string; user_id: string;
          role: string; joined_at: string | null; left_at: string | null;
        };
        Insert: { meeting_id: string; user_id: string; role?: string; };
        Update: { joined_at?: string; left_at?: string; };
        Relationships: [];
      };
      meeting_threads: {
        Row: { id: string; meeting_id: string; created_at: string; };
        Insert: { meeting_id: string; };
        Update: never;
        Relationships: [];
      };
      meeting_messages: {
        Row: {
          id: string; thread_id: string; sender_id: string;
          content: string; created_at: string;
        };
        Insert: { thread_id: string; sender_id: string; content: string; };
        Update: never;
        Relationships: [];
      };
      introductions: {
        Row: {
          id: string; requester_id: string; introducer_id: string; target_id: string;
          status: string; message: string | null;
          created_at: string; updated_at: string;
        };
        Insert: {
          requester_id: string; introducer_id: string; target_id: string;
          message?: string | null; status?: string;
        };
        Update: { status?: string; };
        Relationships: [];
      };
      communities: {
        Row: {
          id: string; name: string; slug: string; owner_id: string;
          member_count: number; max_free_members: number;
          subscription_status: string;
          stripe_customer_id: string | null; stripe_subscription_id: string | null;
          settings: Json; created_at: string; updated_at: string;
        };
        Insert: { name: string; slug: string; owner_id: string; };
        Update: { member_count?: number; subscription_status?: string; settings?: Json; };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      handle_new_user: {
        Args: Record<string, never>;
        Returns: void;
      };
      purge_ai_data_on_delete: {
        Args: { p_user_id: string };
        Returns: void;
      };
      get_public_ai_profiles: {
        Args: { p_user_id: string };
        Returns: {
          user_id: string;
          aggregated_skills: Json[];
          aggregated_offerings: Json[];
          communication_profile: Json;
          analysis_count: number;
        }[];
      };
    };
    Enums: {
      notification_type: NotificationType;
      connection_status: ConnectionStatus;
      transcript_status: TranscriptStatus;
    };
  };
}
