// This file will be auto-generated by: supabase gen types typescript
// For now, define a minimal placeholder so imports work.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type NotificationType =
  | "connection_request"
  | "meeting_request"
  | "meeting_confirmed"
  | "meeting_summary"
  | "introduction_request"
  | "introduction_completed"
  | "new_match_weekly"
  | "new_match_high"
  | "mutual_match"
  | "maturity_up"
  | "contact_exchange"
  | "intervention_alert"
  | "followup_reminder"
  | "chat_message"
  | "referral_signed_up"
  | "referral_paying"
  | "system";

export type ConnectionStatus =
  | "pending"
  | "accepted"
  | "declined"
  | "cancelled"
  | "disconnected"
  | "blocked"
  | "reaccepted";

export type TranscriptStatus =
  | "pending"
  | "fetching"
  | "ready"
  | "analyzing"
  | "analyzed"
  | "error";

 
type R = { Relationships: [] };

export interface Database {
  public: {
    Tables: {
      user_profiles: {
        Row: {
          id: string;
          name: string;
          email: string;
          company: string | null;
          position: string | null;
          industry: string | null;
          bio: string | null;
          avatar_url: string | null;
          cover_url: string | null;
          contact_info: string | null;
          timezone: string;
          is_admin: boolean;
          is_active: boolean;
          is_agency: boolean;
          linkedin_id: string | null;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email: string;
          company?: string | null;
          position?: string | null;
          industry?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          cover_url?: string | null;
          contact_info?: string | null;
          timezone?: string;
          is_admin?: boolean;
          is_active?: boolean;
          is_agency?: boolean;
          stripe_customer_id?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["user_profiles"]["Insert"]>;
        Relationships: [];
      };
      connections: {
        Row: {
          id: string;
          user_id: string;
          connected_user_id: string;
          status: ConnectionStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          connected_user_id: string;
          status?: ConnectionStatus;
        };
        Update: {
          status?: ConnectionStatus;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: NotificationType;
          title: string;
          message: string;
          link: string | null;
          actions: Json | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          type: NotificationType;
          title: string;
          message: string;
          link?: string | null;
          actions?: Json | null;
          is_read?: boolean;
        };
        Update: {
          is_read?: boolean;
        };
        Relationships: [];
      };
      meeting_transcripts: {
        Row: {
          id: string;
          tldv_meeting_id: string;
          title: string | null;
          meeting_date: string | null;
          full_text: string | null;
          status: TranscriptStatus;
          error_message: string | null;
          fetched_at: string | null;
          created_at: string;
        };
        Insert: {
          tldv_meeting_id: string;
          title?: string | null;
          meeting_date?: string | null;
          full_text?: string | null;
          status?: TranscriptStatus;
        };
        Update: Partial<
          Database["public"]["Tables"]["meeting_transcripts"]["Insert"]
        >;
        Relationships: [];
      };
      meeting_participants: {
        Row: {
          id: string;
          transcript_id: string;
          user_id: string | null;
          speaker_name: string;
          email: string | null;
          speaking_ratio: number | null;
          is_linked: boolean;
          linked_method: string | null;
          created_at: string;
        };
        Insert: {
          transcript_id: string;
          speaker_name: string;
          user_id?: string | null;
          email?: string | null;
          speaking_ratio?: number | null;
          is_linked?: boolean;
          linked_method?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["meeting_participants"]["Insert"]
        >;
        Relationships: [];
      };
      transcript_insights: {
        Row: {
          id: string;
          transcript_id: string;
          participant_id: string;
          demonstrated_skills: string[];
          expressed_needs: Json[];
          offered_capabilities: Json[];
          communication_traits: Json;
          key_statements: string[];
          engagement_metrics: Json;
          confidence_score: number | null;
          prompt_version: string | null;
          created_at: string;
        };
        Insert: {
          transcript_id: string;
          participant_id: string;
          demonstrated_skills?: string[];
          expressed_needs?: Json[];
          offered_capabilities?: Json[];
          communication_traits?: Json;
          key_statements?: string[];
          engagement_metrics?: Json;
          confidence_score?: number | null;
          prompt_version?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["transcript_insights"]["Insert"]
        >;
        Relationships: [];
      };
      member_ai_profiles_v2: {
        Row: {
          id: string;
          user_id: string;
          aggregated_skills: Json[];
          aggregated_needs: Json[];
          aggregated_offerings: Json[];
          communication_profile: Json;
          analysis_count: number;
          last_analyzed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          aggregated_skills?: Json[];
          aggregated_needs?: Json[];
          aggregated_offerings?: Json[];
          communication_profile?: Json;
          analysis_count?: number;
          last_analyzed_at?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["member_ai_profiles_v2"]["Insert"]
        >;
        Relationships: [];
      };
      matching_scores_v4: {
        Row: {
          id: string;
          viewer_id: string;
          target_id: string;
          need_offer_score: number;
          reverse_match: number;
          expertise_fit: number;
          topic_alignment: number;
          engagement_value: number;
          history_score: number;
          total_score: number;
          confidence: number;
          phase: string;
          score_reasons: Json;
          notify_tier: string | null;
          is_stale: boolean;
          config_version: string;
          algorithm_version: string;
          calculated_at: string;
        };
        Insert: {
          viewer_id: string;
          target_id: string;
          need_offer_score?: number;
          reverse_match?: number;
          expertise_fit?: number;
          topic_alignment?: number;
          engagement_value?: number;
          history_score?: number;
          total_score?: number;
          confidence?: number;
          phase?: string;
          score_reasons?: Json;
          notify_tier?: string | null;
          is_stale?: boolean;
          config_version?: string;
          algorithm_version?: string;
          calculated_at?: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["matching_scores_v4"]["Insert"]
        >;
        Relationships: [];
      };
      user_conversation_vectors: {
        Row: {
          id: string;
          user_id: string;
          need_vectors: Json;
          offer_vectors: Json;
          expertise_vectors: Json;
          topic_vectors: Json;
          engagement_signature: Json;
          evidence_index: Json;
          hidden_items: Json;
          analysis_count: number;
          meeting_ids: string[];
          last_analyzed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          need_vectors?: Json;
          offer_vectors?: Json;
          expertise_vectors?: Json;
          topic_vectors?: Json;
          engagement_signature?: Json;
          evidence_index?: Json;
          hidden_items?: Json;
          analysis_count?: number;
          meeting_ids?: string[];
          last_analyzed_at?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["user_conversation_vectors"]["Insert"]
        >;
        Relationships: [];
      };
      scoring_config: {
        Row: {
          id: string;
          version_id: string;
          weights_json: Json;
          alpha_table_json: Json;
          boost_params_json: Json;
          validated_accuracy: number | null;
          validation_details: Json;
          is_active: boolean;
          applied_at: string | null;
          created_at: string;
        };
        Insert: {
          version_id: string;
          weights_json?: Json;
          alpha_table_json?: Json;
          boost_params_json?: Json;
          validated_accuracy?: number | null;
          validation_details?: Json;
          is_active?: boolean;
          applied_at?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["scoring_config"]["Insert"]
        >;
        Relationships: [];
      };
      correction_log: {
        Row: {
          id: string;
          user_id: string;
          vector_id: string | null;
          correction_type: string;
          correction_text: string | null;
          original_text: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          vector_id?: string | null;
          correction_type: string;
          correction_text?: string | null;
          original_text: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["correction_log"]["Insert"]
        >;
        Relationships: [];
      };
      feedback_log: {
        Row: {
          id: string;
          viewer_id: string;
          target_id: string;
          rating: number;
          value_tags: Json;
          haiku_no_at_time: number | null;
          haiku_rv_at_time: number | null;
          config_version: string | null;
          created_at: string;
        };
        Insert: {
          viewer_id: string;
          target_id: string;
          rating: number;
          value_tags?: Json;
          haiku_no_at_time?: number | null;
          haiku_rv_at_time?: number | null;
          config_version?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["feedback_log"]["Insert"]
        >;
        Relationships: [];
      };
      mutual_match_notifications: {
        Row: {
          id: string;
          user_a_id: string;
          user_b_id: string;
          notified_at: string;
        };
        Insert: {
          user_a_id: string;
          user_b_id: string;
        };
        Update: never;
        Relationships: [];
      };
      // match_requests / match_connections は meeting_requests / connections に統合済み (削除)
      profile_views: {
        Row: {
          id: string;
          viewer_id: string;
          viewed_user_id: string;
          view_duration: number | null;
          viewed_at: string;
        };
        Insert: {
          viewer_id: string;
          viewed_user_id: string;
          view_duration?: number | null;
        };
        Update: never;
        Relationships: [];
      };
      bookmarks: {
        Row: {
          id: string;
          user_id: string;
          bookmarked_user_id: string;
          note: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          bookmarked_user_id: string;
          note?: string | null;
        };
        Update: {
          note?: string | null;
        };
        Relationships: [];
      };
      settings: {
        Row: {
          id: string;
          user_id: string;
          theme: string;
          notifications_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          theme?: string;
          notifications_enabled?: boolean;
        };
        Update: {
          theme?: string;
          notifications_enabled?: boolean;
        };
        Relationships: [];
      };
      prompt_versions: {
        Row: {
          id: string;
          name: string;
          version: string;
          template: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          name: string;
          version: string;
          template: string;
          is_active?: boolean;
        };
        Update: {
          is_active?: boolean;
          template?: string;
        };
        Relationships: [];
      };
      login_sessions: {
        Row: {
          id: string;
          user_id: string;
          device: string | null;
          browser: string | null;
          ip_address: string | null;
          user_agent: string | null;
          os: string | null;
          referrer: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          device?: string | null;
          browser?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          os?: string | null;
          referrer?: string | null;
        };
        Update: never;
        Relationships: [];
      };
      invitation_codes: {
        Row: {
          id: string;
          code: string;
          created_by: string | null;
          used_by: string | null;
          max_uses: number;
          use_count: number;
          expires_at: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          code: string;
          created_by?: string | null;
          max_uses?: number;
          expires_at?: string | null;
        };
        Update: {
          used_by?: string | null;
          use_count?: number;
          is_active?: boolean;
        };
        Relationships: [];
      };
      user_goals: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          context: string | null;
          /** 00013_goals_offerings_taxonomy_v2 で追加。Z4 detail 文字数評価で参照。 */
          detail: string | null;
          confidence: number;
          source: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          type: string;
          context?: string | null;
          detail?: string | null;
          confidence?: number;
          source?: string;
        };
        Update: {
          context?: string | null;
          detail?: string | null;
          confidence?: number;
        };
        Relationships: [];
      };
      user_offerings: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          context: string | null;
          /** 00013_goals_offerings_taxonomy_v2 で追加。Z4 detail 文字数評価で参照。 */
          detail: string | null;
          confidence: number;
          source: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          type: string;
          context?: string | null;
          detail?: string | null;
          confidence?: number;
          source?: string;
        };
        Update: {
          context?: string | null;
          detail?: string | null;
          confidence?: number;
        };
        Relationships: [];
      };
      meeting_requests: {
        Row: {
          id: string; requester_id: string; target_id: string;
          message: string | null; proposed_times: Json;
          status: string; created_at: string; updated_at: string;
        };
        Insert: {
          requester_id: string; target_id: string;
          message?: string | null; proposed_times?: Json; status?: string;
        };
        Update: { status?: string; };
        Relationships: [];
      };
      meetings: {
        Row: {
          id: string; request_id: string | null; title: string | null;
          scheduled_at: string; duration_min: number; platform: string;
          meeting_url: string | null; status: string;
          created_at: string; updated_at: string;
        };
        Insert: {
          request_id?: string | null; title?: string | null;
          scheduled_at: string; duration_min?: number; platform?: string;
          meeting_url?: string | null; status?: string;
        };
        Update: { title?: string; status?: string; meeting_url?: string; updated_at?: string; };
        Relationships: [];
      };
      meeting_participants_v2: {
        Row: {
          id: string; meeting_id: string; user_id: string;
          role: string; joined_at: string | null; left_at: string | null;
        };
        Insert: { meeting_id: string; user_id: string; role?: string; };
        Update: { joined_at?: string; left_at?: string; };
        Relationships: [];
      };
      meeting_threads: {
        Row: { id: string; meeting_id: string; created_at: string; };
        Insert: { meeting_id: string; };
        Update: never;
        Relationships: [];
      };
      meeting_messages: {
        Row: {
          id: string; thread_id: string; sender_id: string;
          content: string; created_at: string;
        };
        Insert: { thread_id: string; sender_id: string; content: string; };
        Update: never;
        Relationships: [];
      };
      introductions: {
        Row: {
          id: string; requester_id: string; introducer_id: string; target_id: string;
          status: string; message: string | null;
          created_at: string; updated_at: string;
        };
        Insert: {
          requester_id: string; introducer_id: string; target_id: string;
          message?: string | null; status?: string;
        };
        Update: { status?: string; };
        Relationships: [];
      };
      communities: {
        Row: {
          id: string; name: string; slug: string; owner_id: string;
          member_count: number; max_free_members: number;
          subscription_status: string;
          stripe_customer_id: string | null; stripe_subscription_id: string | null;
          settings: Json; created_at: string; updated_at: string;
        };
        Insert: { name: string; slug: string; owner_id: string; };
        Update: { member_count?: number; subscription_status?: string; settings?: Json; };
        Relationships: [];
      };
      calendar_connections: {
        Row: {
          id: string;
          user_id: string;
          provider: "google" | "microsoft" | "ics_feed";
          provider_email: string;
          access_token_enc: string;
          // NOTE: SQL schema has NOT NULL but ICS feed connections need null.
          // TODO: Update SQL migration to allow NULL for refresh_token_enc.
          refresh_token_enc: string | null;
          token_expires_at: string | null;
          ics_url: string | null;
          ics_etag: string | null;
          sync_cursor: string | null;
          last_synced_at: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          provider: "google" | "microsoft" | "ics_feed";
          provider_email: string;
          access_token_enc: string;
          refresh_token_enc?: string | null;
          token_expires_at?: string | null;
          ics_url?: string | null;
          ics_etag?: string | null;
          sync_cursor?: string | null;
          last_synced_at?: string | null;
          is_active?: boolean;
        };
        Update: {
          provider?: "google" | "microsoft" | "ics_feed";
          provider_email?: string;
          access_token_enc?: string;
          refresh_token_enc?: string | null;
          token_expires_at?: string | null;
          ics_url?: string | null;
          ics_etag?: string | null;
          sync_cursor?: string | null;
          last_synced_at?: string | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      calendar_events: {
        Row: {
          id: string;
          connection_id: string;
          user_id: string;
          external_event_id: string;
          title: string | null;
          start_at: string;
          end_at: string;
          video_url: string | null;
          video_platform: string | null;
          attendee_emails: string[];
          is_interconnect: boolean;
          recording_enabled: boolean;
          linked_meeting_id: string | null;
          etag: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          connection_id: string;
          user_id: string;
          external_event_id: string;
          title?: string | null;
          start_at: string;
          end_at: string;
          video_url?: string | null;
          video_platform?: string | null;
          attendee_emails?: string[];
          is_interconnect?: boolean;
          recording_enabled?: boolean;
          linked_meeting_id?: string | null;
          etag?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["calendar_events"]["Insert"]
        >;
        Relationships: [];
      };
      chat_rooms: {
        Row: {
          id: string;
          connection_id: string;
          user_a_id: string;
          user_b_id: string;
          last_message_at: string | null;
          last_message_preview: string | null;
          last_message_sender_id: string | null;
          last_message_content_type: string | null;
          created_at: string;
        };
        Insert: {
          connection_id: string;
          user_a_id: string;
          user_b_id: string;
          last_message_at?: string | null;
          last_message_preview?: string | null;
          last_message_sender_id?: string | null;
          last_message_content_type?: string | null;
        };
        Update: {
          last_message_at?: string | null;
          last_message_preview?: string | null;
          last_message_sender_id?: string | null;
          last_message_content_type?: string | null;
        };
        Relationships: [];
      };
      chat_messages: {
        Row: {
          id: string;
          room_id: string;
          sender_id: string;
          content: string;
          content_type: "text" | "image" | "file" | "scheduling_card" | "meeting_suggestion" | "meeting_confirmed";
          payload: Json | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          room_id: string;
          sender_id: string;
          content: string;
          content_type?: "text" | "image" | "file" | "scheduling_card" | "meeting_suggestion" | "meeting_confirmed";
          payload?: Json | null;
          is_read?: boolean;
        };
        Update: {
          is_read?: boolean;
        };
        Relationships: [];
      };
      audit_logs: {
        // 旧カラム (user_id/entity_type/entity_id/metadata/ip_address) は migration 00045 で物理削除済
        Row: {
          // 00027 で uuid に統一 (旧 number は誤った型定義)
          id: string;
          actor_id: string | null;
          action: string;
          target_type: string | null;
          target_id: string | null;
          payload: Json | null;
          ip: string | null;
          ua: string | null;
          created_at: string;
        };
        Insert: {
          actor_id: string;
          action: string;
          target_type?: string | null;
          target_id?: string | null;
          payload?: Json | null;
          ip?: string | null;
          ua?: string | null;
        };
        Update: never; // WORM trigger で UPDATE/DELETE 拒否
        Relationships: [];
      };
      rate_limits: {
        Row: {
          user_id: string;
          bucket: string;
          window_start: string;
          count: number;
        };
        Insert: {
          user_id: string;
          bucket: string;
          window_start: string;
          count?: number;
        };
        Update: {
          count?: number;
        };
        Relationships: [];
      };
      meeting_data_import_requests: {
        Row: {
          id: string;
          user_id: string;
          status: "pending" | "processing" | "done" | "rejected" | "cancelled";
          message: string | null;
          source: "tldv" | "manual_csv" | "other";
          admin_note: string | null;
          processed_at: string | null;
          processed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          status?: "pending" | "processing" | "done" | "rejected" | "cancelled";
          message?: string | null;
          source?: "tldv" | "manual_csv" | "other";
          admin_note?: string | null;
        };
        Update: {
          status?: "pending" | "processing" | "done" | "rejected" | "cancelled";
          message?: string | null;
          admin_note?: string | null;
          processed_at?: string | null;
          processed_by?: string | null;
        };
        Relationships: [];
      };
      chat_message_idempotency_keys: {
        Row: {
          user_id: string;
          idempotency_key: string;
          message_id: string;
          body_hash: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          idempotency_key: string;
          message_id: string;
          body_hash?: string;
        };
        Update: never;
        Relationships: [];
      };
      chat_analysis: {
        Row: {
          id: string;
          room_id: string;
          analyzed_up_to_id: string;
          extracted_topics: Json;
          extracted_needs: Json;
          extracted_offers: Json;
          engagement_signals: Json;
          analyzed_at: string;
        };
        Insert: {
          room_id: string;
          analyzed_up_to_id: string;
          extracted_topics?: Json;
          extracted_needs?: Json;
          extracted_offers?: Json;
          engagement_signals?: Json;
        };
        Update: Partial<
          Database["public"]["Tables"]["chat_analysis"]["Insert"]
        >;
        Relationships: [];
      };
      availability_rules: {
        Row: {
          id: string;
          user_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          user_id: string;
          day_of_week: number;
          start_time: string;
          end_time: string;
          is_active?: boolean;
        };
        Update: {
          day_of_week?: number;
          start_time?: string;
          end_time?: string;
          is_active?: boolean;
        };
        Relationships: [];
      };
      availability_overrides: {
        Row: {
          id: string;
          user_id: string;
          target_date: string;
          override_type: string;
          start_time: string | null;
          end_time: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          target_date: string;
          override_type: string;
          start_time?: string | null;
          end_time?: string | null;
        };
        Update: {
          target_date?: string;
          override_type?: string;
          start_time?: string | null;
          end_time?: string | null;
        };
        Relationships: [];
      };
      job_queue: {
        Row: {
          id: string;
          type: string;
          payload: Json;
          status: string;
          priority: number;
          attempts: number;
          max_attempts: number;
          scheduled_at: string;
          locked_at: string | null;
          locked_by: string | null;
          completed_at: string | null;
          last_error: string | null;
          created_at: string;
        };
        Insert: {
          type: string;
          payload: Json;
          status?: string;
          priority?: number;
          attempts?: number;
          max_attempts?: number;
          scheduled_at?: string;
          locked_at?: string | null;
          locked_by?: string | null;
          completed_at?: string | null;
          last_error?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["job_queue"]["Insert"]>;
        Relationships: [];
      };
      judge_pair_cache: {
        Row: {
          id: string;
          viewer_id: string;
          target_id: string;
          need_idx: number;
          offer_idx: number;
          h_no: number;
          h_rv: number;
          reason_no: string | null;
          reason_rv: string | null;
          prompt_version: string;
          judged_at: string;
        };
        Insert: {
          viewer_id: string;
          target_id: string;
          need_idx: number;
          offer_idx: number;
          h_no?: number;
          h_rv?: number;
          reason_no?: string | null;
          reason_rv?: string | null;
          prompt_version?: string;
          judged_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["judge_pair_cache"]["Insert"]>;
        Relationships: [];
      };
      judge_quota_log: {
        Row: {
          id: string;
          viewer_id: string;
          quota_date: string;
          pairs_used: number;
          updated_at: string;
        };
        Insert: {
          viewer_id: string;
          quota_date?: string;
          pairs_used?: number;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["judge_quota_log"]["Insert"]>;
        Relationships: [];
      };
      agencies: {
        Row: {
          user_id: string;
          status: "pending" | "approved" | "suspended" | "rejected";
          applied_at: string;
          approved_at: string | null;
          approved_by: string | null;
          suspended_at: string | null;
          suspended_by: string | null;
          total_clicks: number;
          total_referrals: number;
          total_earnings_jpy: number;
          current_balance_jpy: number;
          current_rank: "bronze" | "silver" | "gold" | "platinum" | "diamond";
          commission_rate: number;
          payout_method: string | null;
          payout_info_encrypted: string | null;
          min_withdrawal_jpy: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          status?: "pending" | "approved" | "suspended" | "rejected";
          approved_at?: string | null;
          approved_by?: string | null;
          suspended_at?: string | null;
          suspended_by?: string | null;
          total_clicks?: number;
          total_referrals?: number;
          total_earnings_jpy?: number;
          current_balance_jpy?: number;
          current_rank?: "bronze" | "silver" | "gold" | "platinum" | "diamond";
          commission_rate?: number;
          payout_method?: string | null;
          payout_info_encrypted?: string | null;
          min_withdrawal_jpy?: number;
        };
        Update: {
          status?: "pending" | "approved" | "suspended" | "rejected";
          approved_at?: string | null;
          approved_by?: string | null;
          suspended_at?: string | null;
          suspended_by?: string | null;
          total_clicks?: number;
          total_referrals?: number;
          total_earnings_jpy?: number;
          current_balance_jpy?: number;
          current_rank?: "bronze" | "silver" | "gold" | "platinum" | "diamond";
          commission_rate?: number;
          payout_method?: string | null;
          payout_info_encrypted?: string | null;
          min_withdrawal_jpy?: number;
        };
        Relationships: [];
      };
      agency_applications: {
        Row: {
          id: string;
          applicant_id: string;
          status: "pending" | "approved" | "rejected";
          applicant_note: string | null;
          admin_note: string | null;
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          applicant_id: string;
          status?: "pending" | "approved" | "rejected";
          applicant_note?: string | null;
          admin_note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
        };
        Update: {
          status?: "pending" | "approved" | "rejected";
          applicant_note?: string | null;
          admin_note?: string | null;
          reviewed_by?: string | null;
          reviewed_at?: string | null;
        };
        Relationships: [];
      };
      referral_links: {
        Row: {
          id: string;
          agency_user_id: string;
          code: string;
          label: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          agency_user_id: string;
          code: string;
          label?: string | null;
          is_active?: boolean;
        };
        Update: {
          label?: string | null;
          is_active?: boolean;
        };
        Relationships: [];
      };
      referral_clicks: {
        Row: {
          id: string;
          referral_link_id: string;
          visitor_id: string;
          ip_hash: string | null;
          user_agent: string | null;
          referrer: string | null;
          converted_to_referral_id: string | null;
          clicked_at: string;
        };
        Insert: {
          referral_link_id: string;
          visitor_id: string;
          ip_hash?: string | null;
          user_agent?: string | null;
          referrer?: string | null;
          converted_to_referral_id?: string | null;
        };
        Update: {
          converted_to_referral_id?: string | null;
        };
        Relationships: [];
      };
      referrals: {
        Row: {
          id: string;
          referral_link_id: string;
          referred_user_id: string;
          status: "signed_up" | "paying" | "churned" | "refunded";
          signed_up_at: string;
          first_payment_at: string | null;
          churned_at: string | null;
          refunded_at: string | null;
        };
        Insert: {
          referral_link_id: string;
          referred_user_id: string;
          status?: "signed_up" | "paying" | "churned" | "refunded";
          first_payment_at?: string | null;
          churned_at?: string | null;
          refunded_at?: string | null;
        };
        Update: {
          status?: "signed_up" | "paying" | "churned" | "refunded";
          first_payment_at?: string | null;
          churned_at?: string | null;
          refunded_at?: string | null;
        };
        Relationships: [];
      };
      commissions: {
        Row: {
          id: string;
          agency_user_id: string;
          referral_id: string;
          amount_jpy: number;
          rate: number;
          basis_jpy: number;
          status: "pending" | "confirmed" | "paid" | "reversed";
          payout_id: string | null;
          created_at: string;
          confirmed_at: string | null;
        };
        Insert: {
          agency_user_id: string;
          referral_id: string;
          amount_jpy: number;
          rate: number;
          basis_jpy: number;
          status?: "pending" | "confirmed" | "paid" | "reversed";
          payout_id?: string | null;
          confirmed_at?: string | null;
        };
        Update: {
          status?: "pending" | "confirmed" | "paid" | "reversed";
          payout_id?: string | null;
          confirmed_at?: string | null;
        };
        Relationships: [];
      };
      payouts: {
        Row: {
          id: string;
          agency_user_id: string;
          amount_jpy: number;
          method: string;
          status: "requested" | "processing" | "completed" | "failed";
          requested_at: string;
          processed_at: string | null;
          failed_reason: string | null;
        };
        Insert: {
          agency_user_id: string;
          amount_jpy: number;
          method: string;
          status?: "requested" | "processing" | "completed" | "failed";
          processed_at?: string | null;
          failed_reason?: string | null;
        };
        Update: {
          status?: "requested" | "processing" | "completed" | "failed";
          processed_at?: string | null;
          failed_reason?: string | null;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          stripe_subscription_id: string;
          stripe_customer_id: string;
          stripe_price_id: string;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          canceled_at: string | null;
          trial_end: string | null;
          last_invoice_amount_jpy: number | null;
          last_invoice_paid_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          stripe_subscription_id: string;
          stripe_customer_id: string;
          stripe_price_id: string;
          status: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          trial_end?: string | null;
          last_invoice_amount_jpy?: number | null;
          last_invoice_paid_at?: string | null;
        };
        Update: {
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          trial_end?: string | null;
          last_invoice_amount_jpy?: number | null;
          last_invoice_paid_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      handle_new_user: {
        Args: Record<string, never>;
        Returns: void;
      };
      purge_ai_data_on_delete: {
        Args: { p_user_id: string };
        Returns: void;
      };
      get_public_ai_profiles: {
        Args: { p_user_id: string };
        Returns: {
          user_id: string;
          aggregated_skills: Json[];
          aggregated_offerings: Json[];
          communication_profile: Json;
          analysis_count: number;
        }[];
      };
      get_unread_counts: {
        Args: Record<string, never>;
        Returns: { room_id: string; unread_count: number }[];
      };
      get_active_referral_count: {
        Args: { p_agency_user_id: string };
        Returns: number;
      };
      check_rate_limit: {
        Args: {
          p_user_id: string;
          p_bucket: string;
          p_limit: number;
          p_window_seconds?: number;
        };
        Returns: boolean;
      };
      lookup_referral_link: {
        Args: { p_code: string };
        Returns: { id: string; is_active: boolean }[];
      };
      record_referral_click: {
        Args: {
          p_link_id: string;
          p_visitor_id: string;
          p_ip_hash: string | null;
          p_user_agent: string | null;
          p_referrer: string | null;
        };
        Returns: string;
      };
      compute_agency_rank: {
        Args: { p_total_referrals: number };
        Returns: string;
      };
      handle_subscription_payment: {
        Args: {
          p_user_id: string;
          p_amount_jpy: number;
          p_stripe_invoice_id: string;
        };
        Returns: undefined;
      };
      handle_subscription_canceled: {
        Args: { p_user_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      notification_type: NotificationType;
      connection_status: ConnectionStatus;
      transcript_status: TranscriptStatus;
    };
  };
}
